services:
  demo-service:
    build: .
    environment:
      - spring.datasource.url=jdbc:postgresql://postgres:5432/mydatabase
      - spring.datasource.username=myuser
      - spring.datasource.password=secret
    ports:
      - '8080:8080'
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5432'
